### Importing Libraries and Dataset

In [ ]:
pip install pycaret

In [2]:
import pandas as pd
from pycaret.regression import *

In [3]:
dataset = pd.read_csv("Fuel_cell_performance_data-Full.csv")

In [8]:
dataset1 = dataset.drop(columns=['Target1', 'Target2', 'Target3', 'Target5'])

In [9]:
dataset1.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,Target4
0,52.9,1.33,49.1,37.13,129.43,35.0,0.281,112.7,207,0.55,98.971,2.87,1362,15.9,429,4.19
1,87.6,2.12,48.8,42.10,171.07,37.6,0.153,157.4,188,0.86,101.179,2.34,5130,26.1,1819,5.19
2,73.3,2.72,93.8,20.11,163.69,44.3,0.367,348.7,270,1.87,98.919,2.13,7811,16.7,1763,7.77
3,65.6,2.58,48.1,35.11,63.37,32.5,0.279,321.2,322,1.75,101.560,2.91,1641,32.1,203,8.40
4,39.6,2.58,49.3,32.93,63.40,47.0,0.149,205.6,203,1.55,98.148,1.93,7648,27.5,276,4.75

### Regression Using Pycaret

##### Data PreProcessing

In [33]:
from pycaret.regression import setup

In [34]:
setup1 = setup(
    data=dataset1, 
    target=dataset1["Target4"], 
    session_id=1, 
    train_size=0.7, #70/30 train test split
    normalize=True,  
    transformation=True 
)

##### Comparing all models using Pycaret

In [22]:
comparison = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .              22:32:25
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [23]:
print(comparison)

ExtraTreesRegressor(n_jobs=-1, random_state=1)

We got ExtraTreesRegressor as the best suited model for this dataset

##### Evaluating the model and its deployment

In [30]:
final = finalize_model(comparison)

In [31]:
evaluate_model(final)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [32]:
save_model(final, 'Fuel Cell Predictor')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['F1', 'F2', 'F3', 'F4', 'F5', 'F6',
                                              'F7', 'F8', 'F9', 'F10', 'F11',
                                              'F12', 'F13', 'F14', 'F15',
                                              'Target4_x'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('transformation',
                  TransformerWrapper(transformer=PowerTransformer(standardize=False))),
                 ('normalize', TransformerWrapper(transformer=StandardScaler())),
                 ('actual_estimator',
                  ExtraTreesRegressor(n_jobs=-1, random_state=1))]),
 'Fuel Cell Predictor.pkl')

##### Testing the model on test set

In [26]:
prediction = predict_model(final)

In [27]:
prediction.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,Target4_x,Target4_y,prediction_label
507,82.400002,2.07,60.200001,28.030001,44.189999,32.200001,0.382,198.100006,183,1.67,98.089996,2.59,3382,15.400000,1249,3.33,3.33,3.3089
818,33.000000,2.20,30.200001,42.680000,184.740005,48.000000,0.347,364.700012,154,0.54,96.707001,1.88,3902,18.400000,1279,5.20,5.20,5.1684
452,54.799999,2.72,69.599998,37.040001,177.369995,30.500000,0.225,183.600006,329,0.69,98.980003,2.48,2697,27.200001,268,8.33,8.33,8.3032
368,40.700001,1.39,54.200001,17.510000,64.370003,42.900002,0.254,153.600006,216,1.59,100.334999,2.16,8330,32.799999,503,7.63,7.63,7.6014
242,85.400002,2.60,69.400002,31.320000,158.929993,37.500000,0.264,138.399994,57,1.03,102.808998,2.79,3628,26.400000,717,2.66,2.66,2.6471